### ISSUE TITLE
Day 4 week 4 peer-per code review

### ISSUE THREAD

**Issue by Zeph180** [frempongdev/Testing-Practice#1]
Hello @frempongdev 

With great effort, your project looks good. However, there are a few issues here and there.
Let's try to avoid redundant code in the comments. Ref https://github.com/frempongdev/Testing-Practice/blob/main/index.test.js#L1-L13.
It's good practice to leave a space between the arrow and the brackets when using arrow functions. This makes your codebase readable. Check this out here :point_right: https://github.com/frempongdev/Testing-Practice/blob/main/calculator.js#L3

**Comment by frempongdev** [comment]
Hey @Zeph180, thanks for taking a dive into my project. I have checked your recommendations and i have fixed them. 😉
